@startuml

class ActiveState {
	{field} -validatedBy : String
}


class AnafResult {
	{field} -isVatPayer : boolean
	{field} -name : String
}


class Country <<Entity>>  {
	{field} +@Id id : long
	{field} +iso : String
	{field} +name : String
}


class Customer <<Entity>>  {
	{field} +createdByUsername : String
	{field} +createdDate : LocalDate
	{field} +discountedVat : boolean
	{field} +email : String
	{field} +goldMember : boolean
	{field} +goldMemberRemovalReason : String
	{field} +@Id id : Long
	{field} +legalEntityCode : String
	{field} +name : String
	{field} -validatedBy : String
}


class CustomerContext {
	{field} -validatedBy : String
}


interface CustomerState {
}


class CustomerStateGofExample {
}


class CustomerStateMachine {
}


class CustomerStateMachineExample {
}


enum CustomerStatus {
	{field} +ACTIVE
	{field} +DELETED
	{field} +DRAFT
	{field} +VALIDATED
}


class DeletedState {
}


class DraftState {
}


class Email {
	{field} -body : String
	{field} -cc : List
	{field} -from : String
	{field} -subject : String
	{field} -to : String
}


class EmailBuilder {
	{field} -body : String
	{field} -from : String
	{field} -subject : String
	{field} -to : String
}


class Holder {
}


class InsurancePolicy <<Entity>>  {
	{field} +countryId : Long
	{field} +@Id id : Long
	{field} +valueInEur : BigDecimal
}


class PolicyNotification <<Entity>>  {
	{field} +@Id id : Long
	{field} +time : LocalDateTime
	{field} +title : String
}


class ShippingAddress {
	{field} -city : String
	{field} -street : String
	{field} -zip : String
}


class StateMachineToPlantUml {
}


enum Status {
	{field} +ACTIVE
	{field} +DELETED
	{field} +DRAFT
	{field} +VALIDATED
}


class Transition {
	{field} -guard : Predicate
	{field} -label : String
}


class User {
	{field} -firstName : String
	{field} -lastName : String
	{field} -username : String
	{field} -workEmail : Optional
}


class ValidatedState {
	{field} -validatedBy : String
}




ActiveState ..|>  CustomerState
Customer -->  Country :  @ManyToOne\ncountry
Customer -->  ShippingAddress : shippingAddress
Customer -->  Status : status
CustomerStateMachine "1" o-- "0..*"  CustomerStatus : graph
CustomerStateMachineExample *--  CustomerStateMachine : INSTANCE
DeletedState ..|>  CustomerState
DraftState ..|>  CustomerState
Holder -->  CustomerState : state
InsurancePolicy -->  Customer :  @ManyToOne\ncustomer
PolicyNotification -->  InsurancePolicy :  @ManyToOne\npolicy
Transition *--  CustomerStatus : target
ValidatedState ..|>  CustomerState


@enduml