@startuml
!theme sketchy-outline

package domain {
    class Person {
    }
    class Customer extends Person {
      name
    }
    
    Customer -> "1" Country : lives in
    Customer -> "1" Country : works in
    PolicyNotification "N" ---> "1" InsurancePolicy
    InsurancePolicy --> Customer
}
@enduml
