@startuml Customer Status

[*] --> DRAFT

DRAFT --> VALIDATED : validate(by)
VALIDATED --> ACTIVE : activate()
DRAFT --> DELETED : delete()
VALIDATED --> DELETED : delete()
ACTIVE --> DELETED : delete()

DELETED --> [*]

@enduml
