@startuml
[*] --> DRAFT

DRAFT --> VALIDATED : validate(not null username)
VALIDATED --> ACTIVE : activate()
DRAFT --> DELETED : delete()
VALIDATED --> DELETED : delete()
ACTIVE --> DELETED : delete()

'state DELETED {
'  note right: Final state, can't transition out
'}
@enduml